function createfigure10(y1)
%CREATEFIGURE(Y1)
%  Y1:  matrix of y data
 
%  Auto-generated by MATLAB on 26-Aug-2005 02:51:06
 
%% Create figure
figure1 = figure('FileName','/home/mkovacina/Workspaces/MastersThesis/Data/Auction_10.fig');
 
%% Create axes
axes1 = axes('Parent',figure1);
title(axes1,'Auction: 10 agents, 10 tasks');
xlabel(axes1,'Rounds of Bidding');
ylabel(axes1,'Assignment Cost');
hold(axes1,'all');
 
%% Create mutliple lines using matrix input to plot
plot1 = plot(y1);
set(plot1(1),...
  'Color',[1 0 0],...
  'LineStyle',':',...
  'Marker','o');
 
%% Create legend
legend1 = legend(axes1,{'Assignment Cost','Optimal Cost'});
 
